export type Level = 'Débutant' | 'Intermédiaire' | 'Avancé' | 'Expert';
export type Status = 'À jour' | 'À vérifier' | 'En cours de mise à jour';
export type Tool =
  | 'Apple Business Manager'
  | 'Jamf Pro'
  | 'Jamf School'
  | 'Jamf Protect'
  | 'Jamf Security Cloud'
  | 'Jamf Connect'
  | 'Microsoft Intune'
  | 'Android Enterprise'
  | 'macOS'
  | 'iOS'
  | 'iPadOS';

export interface Lesson {
  id: string;
  title: string;
  duration: string;
  description: string;
}

export interface Course {
  id: string;
  slug: string;
  title: string;
  description: string;
  moduleId: string;
  moduleTitle: string;
  level: Level;
  status: Status;
  lastUpdated: string;
  duration: string;
  objectives: string[];
  prerequisites: string[];
  lessons: Lesson[];
  tools: Tool[];
  certificationRelated: string[];
  order: number;
}

export interface Module {
  id: string;
  slug: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  order: number;
  courses: Course[];
}

// ─── MODULE 1 — Fondations Apple Enterprise ────────────────────────────────

const module1Courses: Course[] = [
  {
    id: 'abm-ecosysteme',
    slug: 'ecosysteme-apple-entreprise',
    title: 'Écosystème Apple en entreprise',
    description: 'Comprendre l\'architecture globale des solutions Apple pour les organisations : appareils, services, gestion et sécurité.',
    moduleId: 'module-1',
    moduleTitle: 'Fondations Apple Enterprise',
    level: 'Débutant',
    status: 'À jour',
    lastUpdated: '2025-01-15',
    duration: '45 min',
    objectives: [
      'Identifier les appareils Apple gérés en entreprise (Mac, iPhone, iPad)',
      'Comprendre le rôle d\'Apple Business Manager',
      'Distinguer les solutions MDM disponibles',
      'Appréhender la stratégie Zero-Touch Deployment',
    ],
    prerequisites: [],
    lessons: [
      { id: 'l1', title: 'Les appareils Apple en entreprise', duration: '10 min', description: 'Mac, iPhone, iPad : usages et spécificités.' },
      { id: 'l2', title: 'Services Apple natifs', duration: '10 min', description: 'iCloud, App Store, Developer ID, Notarization.' },
      { id: 'l3', title: 'Solutions MDM du marché', duration: '15 min', description: 'Jamf, Intune, comparatif fonctionnel.' },
      { id: 'l4', title: 'Concepts Zero-Touch Deployment', duration: '10 min', description: 'ADE, ABM, enrôlement automatique.' },
    ],
    tools: ['Apple Business Manager', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Apple Device Support', 'Apple Deployment and Management'],
    order: 1,
  },
  {
    id: 'abm-intro',
    slug: 'apple-business-manager',
    title: 'Apple Business Manager (ABM)',
    description: 'Maîtriser le portail ABM pour gérer les appareils, les applications et les comptes Managed Apple dans votre organisation.',
    moduleId: 'module-1',
    moduleTitle: 'Fondations Apple Enterprise',
    level: 'Débutant',
    status: 'À jour',
    lastUpdated: '2025-01-20',
    duration: '1h 15min',
    objectives: [
      'Créer et configurer un compte Apple Business Manager',
      'Associer des MDM servers à ABM',
      'Gérer les appareils achetés et leur assignation',
      'Distribuer des applications via Apps & Books',
    ],
    prerequisites: ['ecosysteme-apple-entreprise'],
    lessons: [
      { id: 'l1', title: 'Présentation et inscription ABM', duration: '15 min', description: 'Processus de création du compte organisation.' },
      { id: 'l2', title: 'Interface et navigation ABM', duration: '15 min', description: 'Portail web : sections, rôles, paramètres.' },
      { id: 'l3', title: 'Ajout de MDM Servers', duration: '20 min', description: 'Liaison Jamf Pro / Intune avec ABM.' },
      { id: 'l4', title: 'Gestion des appareils ABM', duration: '15 min', description: 'Appareils achetés, assignation, réassignation.' },
      { id: 'l5', title: 'Rôles et permissions', duration: '10 min', description: 'Administrateur, gestionnaire, People Manager.' },
    ],
    tools: ['Apple Business Manager'],
    certificationRelated: ['Apple Deployment and Management', 'Jamf 100'],
    order: 2,
  },
  {
    id: 'abm-managed-accounts',
    slug: 'managed-apple-accounts',
    title: 'Managed Apple Accounts',
    description: 'Configurer et gérer les comptes Apple gérés pour les utilisateurs de l\'organisation via ABM ou fédération avec Azure AD / Google.',
    moduleId: 'module-1',
    moduleTitle: 'Fondations Apple Enterprise',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-02-01',
    duration: '50 min',
    objectives: [
      'Comprendre la différence entre Apple ID personnel et Managed Apple Account',
      'Créer des comptes manuellement ou via SCIM',
      'Fédérer ABM avec Microsoft Entra ID ou Google Workspace',
      'Gérer les mots de passe et la récupération',
    ],
    prerequisites: ['apple-business-manager'],
    lessons: [
      { id: 'l1', title: 'Managed Apple Account vs Apple ID', duration: '10 min', description: 'Différences, restrictions et capacités.' },
      { id: 'l2', title: 'Création manuelle et CSV', duration: '15 min', description: 'Import en masse via fichier CSV.' },
      { id: 'l3', title: 'Fédération Microsoft Entra ID', duration: '15 min', description: 'SCIM provisioning, SSO, synchronisation.' },
      { id: 'l4', title: 'Gestion des mots de passe', duration: '10 min', description: 'Réinitialisation, politique, récupération.' },
    ],
    tools: ['Apple Business Manager'],
    certificationRelated: ['Apple Deployment and Management'],
    order: 3,
  },
  {
    id: 'abm-apps-books',
    slug: 'apps-et-books',
    title: 'Apps & Books — Distribution d\'applications',
    description: 'Acheter, gérer et distribuer des applications iOS, iPadOS et macOS via ABM en mode sans friction pour les utilisateurs.',
    moduleId: 'module-1',
    moduleTitle: 'Fondations Apple Enterprise',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-02-10',
    duration: '45 min',
    objectives: [
      'Acheter des licences d\'applications en volume (VPP)',
      'Assigner des apps à des appareils ou utilisateurs',
      'Révoquer et réassigner des licences',
      'Distribuer des apps Custom (B2B)',
    ],
    prerequisites: ['apple-business-manager'],
    lessons: [
      { id: 'l1', title: 'Volume Purchase Program (VPP)', duration: '10 min', description: 'Historique et évolution vers Apps & Books.' },
      { id: 'l2', title: 'Achat de licences en volume', duration: '10 min', description: 'Processus d\'achat et gestion des crédits.' },
      { id: 'l3', title: 'Distribution aux appareils vs utilisateurs', duration: '15 min', description: 'Assignation device-based et user-based.' },
      { id: 'l4', title: 'Apps Custom et B2B', duration: '10 min', description: 'Applications propriétaires, Custom Apps.' },
    ],
    tools: ['Apple Business Manager', 'Jamf Pro', 'Microsoft Intune'],
    certificationRelated: ['Apple Deployment and Management'],
    order: 4,
  },
  {
    id: 'abm-ade',
    slug: 'automated-device-enrollment',
    title: 'Automated Device Enrollment (ADE)',
    description: 'Configurer l\'enrôlement automatique des appareils Apple via ABM pour un déploiement Zero-Touch en entreprise.',
    moduleId: 'module-1',
    moduleTitle: 'Fondations Apple Enterprise',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-02-15',
    duration: '1h',
    objectives: [
      'Comprendre le fonctionnement du protocole ADE',
      'Créer des profils d\'enrôlement dans Jamf Pro et Intune',
      'Assigner des profils à des appareils dans ABM',
      'Tester un enrôlement Zero-Touch complet',
    ],
    prerequisites: ['apple-business-manager', 'apps-et-books'],
    lessons: [
      { id: 'l1', title: 'Architecture ADE', duration: '15 min', description: 'Comment fonctionne DEP → ADE techniquement.' },
      { id: 'l2', title: 'Profil d\'enrôlement Jamf Pro', duration: '20 min', description: 'PreStage Enrollment, configuration, options.' },
      { id: 'l3', title: 'Profil d\'enrôlement Intune', duration: '15 min', description: 'Enrollment Program Token, profils macOS/iOS.' },
      { id: 'l4', title: 'Test et validation Zero-Touch', duration: '10 min', description: 'Workflow complet de bout en bout.' },
    ],
    tools: ['Apple Business Manager', 'Jamf Pro', 'Microsoft Intune', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Apple Deployment and Management', 'Jamf 100', 'Microsoft MD-102'],
    order: 5,
  },
  {
    id: 'abm-securite',
    slug: 'securite-conformite-apple',
    title: 'Sécurité et conformité Apple',
    description: 'Vue d\'ensemble des mécanismes de sécurité natifs Apple : Secure Enclave, T2/Apple Silicon, FileVault, Gatekeeper, Notarization.',
    moduleId: 'module-1',
    moduleTitle: 'Fondations Apple Enterprise',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-01',
    duration: '55 min',
    objectives: [
      'Comprendre Secure Enclave et Apple Silicon Security',
      'Expliquer le rôle du Secure Boot et Activation Lock',
      'Appréhender FileVault, Gatekeeper, Notarization',
      'Identifier les exigences de conformité CIS Apple',
    ],
    prerequisites: ['ecosysteme-apple-entreprise'],
    lessons: [
      { id: 'l1', title: 'Secure Enclave et puce T2 / Apple Silicon', duration: '15 min', description: 'Hardware security, SEP, Secure Boot.' },
      { id: 'l2', title: 'Activation Lock et MDM Bypass', duration: '10 min', description: 'ABM Bypass, gestion entreprise.' },
      { id: 'l3', title: 'FileVault 2 et chiffrement', duration: '15 min', description: 'XTS-AES-128, recovery key, escrow.' },
      { id: 'l4', title: 'Gatekeeper, Notarization, XProtect', duration: '15 min', description: 'Chaîne de confiance des applications.' },
    ],
    tools: ['macOS', 'iOS', 'iPadOS', 'Apple Business Manager'],
    certificationRelated: ['Apple Device Support', 'Apple Deployment and Management'],
    order: 6,
  },
];

// ─── MODULE 2 — Administration macOS avec Jamf Pro ─────────────────────────

const module2Courses: Course[] = [
  {
    id: 'jamf-intro',
    slug: 'introduction-jamf-pro',
    title: 'Introduction à Jamf Pro',
    description: 'Découvrir l\'architecture de Jamf Pro, son installation, ses composants clés et sa place dans l\'écosystème Apple MDM.',
    moduleId: 'module-2',
    moduleTitle: 'Administration macOS avec Jamf Pro',
    level: 'Débutant',
    status: 'À jour',
    lastUpdated: '2025-01-10',
    duration: '1h',
    objectives: [
      'Décrire l\'architecture Jamf Pro (Jamf Cloud vs On-Premise)',
      'Naviguer dans l\'interface Jamf Pro',
      'Comprendre les composants : Jamf Pro Server, Distribution Point, APNS',
      'Créer les premiers groupes et paramètres de base',
    ],
    prerequisites: ['apple-business-manager'],
    lessons: [
      { id: 'l1', title: 'Architecture Jamf Pro', duration: '15 min', description: 'Jamf Cloud, On-Premise, composants clés.' },
      { id: 'l2', title: 'Installation et configuration initiale', duration: '20 min', description: 'Setup assistant, APNS, ABM integration.' },
      { id: 'l3', title: 'Navigation dans Jamf Pro', duration: '15 min', description: 'Computers, Mobile Devices, Users, Settings.' },
      { id: 'l4', title: 'Premiers objets et paramètres', duration: '10 min', description: 'Categories, Buildings, Departments, Sites.' },
    ],
    tools: ['Jamf Pro', 'Apple Business Manager', 'macOS'],
    certificationRelated: ['Jamf 100', 'Jamf 200'],
    order: 1,
  },
  {
    id: 'jamf-enrolement-macos',
    slug: 'enrolement-macos-jamf',
    title: 'Enrôlement macOS avec Jamf Pro',
    description: 'Configurer et réaliser l\'enrôlement des Mac via ADE, User-Initiated Enrollment et MDM Enrollment Profile.',
    moduleId: 'module-2',
    moduleTitle: 'Administration macOS avec Jamf Pro',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-02-05',
    duration: '1h 30min',
    objectives: [
      'Configurer un PreStage Enrollment pour Mac',
      'Réaliser un enrôlement ADE Zero-Touch',
      'Gérer l\'enrôlement initié par l\'utilisateur',
      'Vérifier l\'inventaire après enrôlement',
    ],
    prerequisites: ['introduction-jamf-pro', 'automated-device-enrollment'],
    lessons: [
      { id: 'l1', title: 'PreStage Enrollment macOS', duration: '25 min', description: 'Configuration, options Setup Assistant, MDM activation.' },
      { id: 'l2', title: 'Enrôlement ADE pas à pas', duration: '25 min', description: 'Demo complète d\'un enrôlement Zero-Touch Mac.' },
      { id: 'l3', title: 'User Initiated Enrollment', duration: '20 min', description: 'Invitation email, MDM profile, cas d\'usage.' },
      { id: 'l4', title: 'Inventaire et vérification', duration: '20 min', description: 'Recon, JAMF Helper, inventory data.' },
    ],
    tools: ['Jamf Pro', 'Apple Business Manager', 'macOS'],
    certificationRelated: ['Jamf 100', 'Jamf 200'],
    order: 2,
  },
  {
    id: 'jamf-config-profiles',
    slug: 'configuration-profiles-jamf',
    title: 'Configuration Profiles macOS',
    description: 'Créer, déployer et gérer des profils de configuration macOS pour enforcer les paramètres système, réseau et sécurité.',
    moduleId: 'module-2',
    moduleTitle: 'Administration macOS avec Jamf Pro',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-02-20',
    duration: '1h 15min',
    objectives: [
      'Créer des profils de configuration dans Jamf Pro',
      'Configurer Wi-Fi, VPN, certificats, restrictions',
      'Déployer des profils à des groupes cibles',
      'Résoudre les conflits entre profils',
    ],
    prerequisites: ['enrolement-macos-jamf'],
    lessons: [
      { id: 'l1', title: 'Structure d\'un profil de configuration', duration: '15 min', description: 'Payloads, UUID, signing, scope.' },
      { id: 'l2', title: 'Payloads essentiels macOS', duration: '25 min', description: 'Wi-Fi, VPN, Restrictions, Login Window, Energy.' },
      { id: 'l3', title: 'Certificats et identités', duration: '20 min', description: 'SCEP, PKCS#12, certificats root CA.' },
      { id: 'l4', title: 'Scope et déploiement ciblé', duration: '15 min', description: 'Smart Groups, exclusions, précédence.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 100', 'Jamf 200'],
    order: 3,
  },
  {
    id: 'jamf-policies',
    slug: 'policies-jamf-pro',
    title: 'Policies Jamf Pro',
    description: 'Maîtriser les Policies Jamf Pro pour automatiser les installations, scripts, mises à jour et actions de maintenance sur les Mac.',
    moduleId: 'module-2',
    moduleTitle: 'Administration macOS avec Jamf Pro',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-01',
    duration: '1h 20min',
    objectives: [
      'Créer des policies de déploiement d\'applications',
      'Configurer les triggers et fréquences d\'exécution',
      'Utiliser les policies pour les scripts Bash',
      'Analyser les logs et résultats des policies',
    ],
    prerequisites: ['configuration-profiles-jamf'],
    lessons: [
      { id: 'l1', title: 'Anatomie d\'une Policy', duration: '20 min', description: 'General, Packages, Scripts, Files & Processes, Scope.' },
      { id: 'l2', title: 'Triggers : Enrollment, Login, Recurring', duration: '20 min', description: 'Déclencheurs, fréquences, checkin.' },
      { id: 'l3', title: 'Déploiement d\'applications PKG', duration: '20 min', description: 'Upload package, FUT, Self Service.' },
      { id: 'l4', title: 'Scripts Bash dans les Policies', duration: '20 min', description: 'Paramètres, before/after, logs.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 100', 'Jamf 170', 'Jamf 200'],
    order: 4,
  },
  {
    id: 'jamf-smart-groups',
    slug: 'smart-groups-jamf',
    title: 'Smart Groups et ciblage dynamique',
    description: 'Exploiter la puissance des Smart Groups Jamf Pro pour cibler précisément les appareils selon leurs attributs dynamiques.',
    moduleId: 'module-2',
    moduleTitle: 'Administration macOS avec Jamf Pro',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-05',
    duration: '55 min',
    objectives: [
      'Créer des Computer Smart Groups avec critères complexes',
      'Combiner les opérateurs AND/OR/NOT',
      'Utiliser les Smart Groups comme scope de déploiement',
      'Créer des groupes basés sur la compliance',
    ],
    prerequisites: ['policies-jamf-pro'],
    lessons: [
      { id: 'l1', title: 'Smart Groups vs Static Groups', duration: '10 min', description: 'Différences, cas d\'usage, performance.' },
      { id: 'l2', title: 'Critères et attributs disponibles', duration: '20 min', description: 'OS, Hardware, Software, Extension Attributes.' },
      { id: 'l3', title: 'Opérateurs logiques complexes', duration: '15 min', description: 'AND, OR, NOT, imbrication.' },
      { id: 'l4', title: 'Smart Groups de conformité', duration: '10 min', description: 'Groupes basés sur FileVault, OS version, compliance.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 100', 'Jamf 200'],
    order: 5,
  },
  {
    id: 'jamf-self-service',
    slug: 'self-service-jamf',
    title: 'Self Service — Portail utilisateur Jamf',
    description: 'Créer et personnaliser le portail Self Service pour offrir aux utilisateurs une expérience autonome d\'installation et de support.',
    moduleId: 'module-2',
    moduleTitle: 'Administration macOS avec Jamf Pro',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-10',
    duration: '50 min',
    objectives: [
      'Configurer Self Service macOS et iOS',
      'Publier des applications et scripts dans Self Service',
      'Personnaliser les catégories et l\'interface',
      'Restreindre l\'accès selon les groupes',
    ],
    prerequisites: ['policies-jamf-pro', 'smart-groups-jamf'],
    lessons: [
      { id: 'l1', title: 'Présentation Self Service', duration: '10 min', description: 'Mac App Store privé, cas d\'usage.' },
      { id: 'l2', title: 'Configuration et branding', duration: '15 min', description: 'Logo, couleurs, nom, icône dock.' },
      { id: 'l3', title: 'Publier apps, scripts, profils', duration: '15 min', description: 'Policies en Self Service, descriptions, icônes.' },
      { id: 'l4', title: 'Catégories et accès par groupe', duration: '10 min', description: 'Organisation, smart group scope.' },
    ],
    tools: ['Jamf Pro', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Jamf 100'],
    order: 6,
  },
  {
    id: 'jamf-patch',
    slug: 'patch-management-jamf',
    title: 'Patch Management avec Jamf Pro',
    description: 'Mettre en place une stratégie robuste de gestion des mises à jour logicielles tiers et macOS avec Jamf Pro.',
    moduleId: 'module-2',
    moduleTitle: 'Administration macOS avec Jamf Pro',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-03-15',
    duration: '1h 10min',
    objectives: [
      'Créer des Patch Management titles',
      'Configurer des Patch Policies automatisées',
      'Générer des rapports de conformité des patchs',
      'Intégrer Nudge pour macOS Updates',
    ],
    prerequisites: ['policies-jamf-pro', 'smart-groups-jamf'],
    lessons: [
      { id: 'l1', title: 'Patch Management dans Jamf Pro', duration: '20 min', description: 'Patch titles, sources, définitions.' },
      { id: 'l2', title: 'Patch Policies et déploiement', duration: '20 min', description: 'Deadlines, grace period, notifications.' },
      { id: 'l3', title: 'Gestion des mises à jour macOS', duration: '20 min', description: 'DDM, Managed Updates, Nudge.' },
      { id: 'l4', title: 'Reporting et tableau de bord', duration: '10 min', description: 'Dashboard patch, rapports de conformité.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 7,
  },
  {
    id: 'jamf-reporting',
    slug: 'reporting-conformite-jamf',
    title: 'Reporting et conformité Jamf Pro',
    description: 'Exploiter les rapports avancés, les dashboards et les smart searches de Jamf Pro pour piloter la conformité du parc.',
    moduleId: 'module-2',
    moduleTitle: 'Administration macOS avec Jamf Pro',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-03-20',
    duration: '55 min',
    objectives: [
      'Créer des Advanced Searches personnalisées',
      'Exporter des rapports CSV pour audits',
      'Configurer des dashboards de conformité',
      'Utiliser les Extension Attributes pour enrichir l\'inventaire',
    ],
    prerequisites: ['smart-groups-jamf', 'patch-management-jamf'],
    lessons: [
      { id: 'l1', title: 'Advanced Computer Search', duration: '15 min', description: 'Critères avancés, colonnes personnalisées.' },
      { id: 'l2', title: 'Extension Attributes', duration: '20 min', description: 'Scripts EA, Text EA, Popup EA.' },
      { id: 'l3', title: 'Rapports et exports', duration: '10 min', description: 'CSV, intégration SIEM, History.' },
      { id: 'l4', title: 'Dashboard de conformité', duration: '10 min', description: 'Widgets, KPI, vue d\'ensemble parc.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 8,
  },
];

// ─── MODULE 3 — Automatisation Jamf Pro ────────────────────────────────────

const module3Courses: Course[] = [
  {
    id: 'jamf-api',
    slug: 'api-jamf-pro',
    title: 'API Jamf Pro',
    description: 'Interagir avec l\'API Jamf Pro (Classic API et Jamf Pro API) pour automatiser les opérations d\'administration.',
    moduleId: 'module-3',
    moduleTitle: 'Automatisation Jamf Pro',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-01',
    duration: '1h 30min',
    objectives: [
      'Comprendre la Classic API et la Jamf Pro API (v1)',
      'Authentifier les appels API avec Bearer Token',
      'Lire, créer et modifier des objets via API',
      'Construire des scripts d\'automatisation Python/Bash',
    ],
    prerequisites: ['reporting-conformite-jamf'],
    lessons: [
      { id: 'l1', title: 'Classic API vs Jamf Pro API', duration: '20 min', description: 'Architecture, endpoints, documentation.' },
      { id: 'l2', title: 'Authentification Bearer Token', duration: '20 min', description: 'Token, refresh, expiration, best practices.' },
      { id: 'l3', title: 'CRUD via API', duration: '30 min', description: 'GET, POST, PUT, DELETE : exemples pratiques.' },
      { id: 'l4', title: 'Scripts d\'automatisation', duration: '20 min', description: 'Bash + curl, Python + requests, exemples réels.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 170', 'Jamf 200'],
    order: 1,
  },
  {
    id: 'jamf-scripting',
    slug: 'scripting-bash-jamf',
    title: 'Scripting Bash pour Jamf Pro',
    description: 'Écrire des scripts Bash robustes, sécurisés et maintenables pour automatiser les tâches d\'administration macOS via Jamf Pro.',
    moduleId: 'module-3',
    moduleTitle: 'Automatisation Jamf Pro',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-05',
    duration: '2h',
    objectives: [
      'Écrire des scripts Bash conformes aux standards Jamf',
      'Utiliser les paramètres Jamf ($4 à $11)',
      'Gérer les logs et la gestion d\'erreurs',
      'Tester et déboguer les scripts en environnement Jamf',
    ],
    prerequisites: ['api-jamf-pro'],
    lessons: [
      { id: 'l1', title: 'Bonnes pratiques Bash pour Jamf', duration: '30 min', description: 'Shebang, set -e, logs, exit codes.' },
      { id: 'l2', title: 'Paramètres Jamf $4 à $11', duration: '20 min', description: 'Passage de paramètres, validation.' },
      { id: 'l3', title: 'Scripts de configuration système', duration: '30 min', description: 'Préférences, plists, defaults write.' },
      { id: 'l4', title: 'Débogage et tests', duration: '30 min', description: 'jamf log, Console.app, test local vs Jamf.' },
      { id: 'l5', title: 'Bibliothèque de scripts réutilisables', duration: '10 min', description: 'Logging function, error handling pattern.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 170', 'Jamf 200'],
    order: 2,
  },
  {
    id: 'jamf-packaging',
    slug: 'packaging-avance-jamf',
    title: 'Packaging avancé avec Jamf Pro',
    description: 'Créer des packages PKG professionnels pour déployer des applications, des configurations et des scripts via Jamf Pro.',
    moduleId: 'module-3',
    moduleTitle: 'Automatisation Jamf Pro',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-10',
    duration: '1h 30min',
    objectives: [
      'Créer des PKG flat avec pkgbuild et productbuild',
      'Utiliser Jamf Composer pour le packaging',
      'Signer les packages avec un Developer ID',
      'Tester les packages avant déploiement',
    ],
    prerequisites: ['scripting-bash-jamf'],
    lessons: [
      { id: 'l1', title: 'Structure d\'un package PKG', duration: '20 min', description: 'Payload, scripts, distribution XML.' },
      { id: 'l2', title: 'pkgbuild et productbuild', duration: '25 min', description: 'CLI, options, exemples pratiques.' },
      { id: 'l3', title: 'Jamf Composer', duration: '25 min', description: 'Snapshot, File System, options avancées.' },
      { id: 'l4', title: 'Signature et notarisation', duration: '20 min', description: 'Developer ID Installer, xcrun notarytool.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 170'],
    order: 3,
  },
  {
    id: 'jamf-zero-touch',
    slug: 'workflows-zero-touch',
    title: 'Workflows Zero-Touch Deployment',
    description: 'Concevoir des workflows Zero-Touch complets pour déployer des Mac prêts à l\'emploi sans aucune intervention manuelle.',
    moduleId: 'module-3',
    moduleTitle: 'Automatisation Jamf Pro',
    level: 'Expert',
    status: 'À jour',
    lastUpdated: '2025-04-15',
    duration: '2h 30min',
    objectives: [
      'Concevoir un workflow Zero-Touch complet bout en bout',
      'Utiliser Jamf Pro Triggers pour orchestrer le déploiement',
      'Intégrer Jamf Connect pour l\'authentification cloud',
      'Valider et tester le workflow dans différents scénarios',
    ],
    prerequisites: ['packaging-avance-jamf', 'api-jamf-pro'],
    lessons: [
      { id: 'l1', title: 'Architecture d\'un workflow Zero-Touch', duration: '30 min', description: 'ABM → Jamf Pro → Configuration → Prêt.' },
      { id: 'l2', title: 'Orchestration par Triggers', duration: '30 min', description: 'Enrollment Complete, login, Custom Triggers.' },
      { id: 'l3', title: 'Gestion de la progression utilisateur', duration: '30 min', description: 'IBM Notifier, DEPNotify, progression.' },
      { id: 'l4', title: 'Tests et edge cases', duration: '30 min', description: 'Réseau limité, restart, erreurs.' },
      { id: 'l5', title: 'Documentation du workflow', duration: '30 min', description: 'Diagrammes, runbook, maintenance.' },
    ],
    tools: ['Jamf Pro', 'Jamf Connect', 'Apple Business Manager', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 4,
  },
  {
    id: 'jamf-remediation',
    slug: 'remediation-automatique-jamf',
    title: 'Remédiation automatique avec Jamf Pro',
    description: 'Mettre en place des mécanismes de détection et de remédiation automatique pour maintenir la conformité du parc.',
    moduleId: 'module-3',
    moduleTitle: 'Automatisation Jamf Pro',
    level: 'Expert',
    status: 'À jour',
    lastUpdated: '2025-04-20',
    duration: '1h 30min',
    objectives: [
      'Créer des Extension Attributes de détection',
      'Construire des Smart Groups de non-conformité',
      'Déclencher des policies de remédiation automatique',
      'Journaliser et auditer les remédiations',
    ],
    prerequisites: ['workflows-zero-touch'],
    lessons: [
      { id: 'l1', title: 'Pattern Detect → Remediate', duration: '20 min', description: 'Architecture EAs + Smart Groups + Policies.' },
      { id: 'l2', title: 'Extension Attributes de compliance', duration: '25 min', description: 'Scripts EA, critères, retours booléens.' },
      { id: 'l3', title: 'Policies de remédiation', duration: 'troisième', description: '30 min', },
      { id: 'l4', title: 'Audit et reporting', duration: '15 min', description: 'History, logs, reporting conformité.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 5,
  },
  {
    id: 'jamf-macos-updates',
    slug: 'gestion-mises-a-jour-macos',
    title: 'Gestion des mises à jour macOS',
    description: 'Maîtriser les stratégies de déploiement des mises à jour macOS avec DDM, Managed Software Update et Nudge.',
    moduleId: 'module-3',
    moduleTitle: 'Automatisation Jamf Pro',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '1h 20min',
    objectives: [
      'Configurer Declarative Device Management (DDM) pour macOS',
      'Déployer les mises à jour macOS avec Managed Software Update',
      'Utiliser Nudge pour les notifications utilisateur',
      'Créer une stratégie multi-vagues de déploiement',
    ],
    prerequisites: ['patch-management-jamf'],
    lessons: [
      { id: 'l1', title: 'Declarative Device Management (DDM)', duration: '25 min', description: 'Architecture DDM, Activations, Assets.' },
      { id: 'l2', title: 'Managed Software Update', duration: '20 min', description: 'Configuration profile, forcer les updates.' },
      { id: 'l3', title: 'Nudge — Notifications macOS Updates', duration: '20 min', description: 'Configuration JSON, stratégie, UX.' },
      { id: 'l4', title: 'Stratégie de déploiement multi-vagues', duration: '15 min', description: 'Pilote, early adopters, production, rollback.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 6,
  },
];

// ─── MODULE 4 — Sécurité Apple avec Jamf ───────────────────────────────────

const module4Courses: Course[] = [
  {
    id: 'jamf-protect-intro',
    slug: 'jamf-protect-introduction',
    title: 'Introduction à Jamf Protect',
    description: 'Découvrir Jamf Protect, solution de sécurité endpoint native Apple, et ses capacités de détection de menaces macOS.',
    moduleId: 'module-4',
    moduleTitle: 'Sécurité Apple avec Jamf',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-10',
    duration: '1h',
    objectives: [
      'Comprendre l\'architecture de Jamf Protect',
      'Déployer l\'agent Jamf Protect via Jamf Pro',
      'Configurer les plans de sécurité (Analytic Baselines)',
      'Interpréter les alertes et les événements de sécurité',
    ],
    prerequisites: ['policies-jamf-pro'],
    lessons: [
      { id: 'l1', title: 'Architecture Jamf Protect', duration: '15 min', description: 'Agent ESF, télémétrie, cloud analytics.' },
      { id: 'l2', title: 'Déploiement de l\'agent', duration: '20 min', description: 'Package Jamf Protect, policy de déploiement.' },
      { id: 'l3', title: 'Plans de sécurité', duration: '15 min', description: 'Baselines CIS, analytics personnalisés.' },
      { id: 'l4', title: 'Console Jamf Protect', duration: '10 min', description: 'Alertes, événements, investigation.' },
    ],
    tools: ['Jamf Protect', 'Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 1,
  },
  {
    id: 'jamf-security-cloud',
    slug: 'jamf-security-cloud',
    title: 'Jamf Security Cloud',
    description: 'Déployer et configurer Jamf Security Cloud pour la protection réseau, le Safe Browsing et la prévention des menaces mobiles.',
    moduleId: 'module-4',
    moduleTitle: 'Sécurité Apple avec Jamf',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-03-20',
    duration: '1h 15min',
    objectives: [
      'Comprendre le rôle de Jamf Security Cloud (ex-Wandera)',
      'Configurer les politiques de sécurité réseau',
      'Déployer la protection sur iOS/iPadOS via Jamf Pro',
      'Analyser les rapports de menaces et de risques',
    ],
    prerequisites: ['jamf-protect-introduction'],
    lessons: [
      { id: 'l1', title: 'Architecture Jamf Security Cloud', duration: '20 min', description: 'MI:RIAM engine, télémétrie réseau, MTD.' },
      { id: 'l2', title: 'Safe Browsing et content filtering', duration: '20 min', description: 'DNS filtering, catégories, exceptions.' },
      { id: 'l3', title: 'Déploiement iOS/macOS', duration: '20 min', description: 'Intégration Jamf Pro, VPN automatique.' },
      { id: 'l4', title: 'Gestion des risques et alertes', duration: '15 min', description: 'Risk score, alertes, remédiation.' },
    ],
    tools: ['Jamf Security Cloud', 'Jamf Pro', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Jamf 200'],
    order: 2,
  },
  {
    id: 'jamf-filevault',
    slug: 'filevault-gestion-jamf',
    title: 'FileVault — Chiffrement macOS avec Jamf',
    description: 'Déployer, gérer et faire du reporting sur FileVault 2 à travers tout le parc macOS via Jamf Pro.',
    moduleId: 'module-4',
    moduleTitle: 'Sécurité Apple avec Jamf',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-02-25',
    duration: '55 min',
    objectives: [
      'Activer FileVault via profil de configuration Jamf',
      'Escrow des clés de récupération dans Jamf Pro',
      'Générer des rapports de chiffrement du parc',
      'Effectuer une rotation des clés FileVault',
    ],
    prerequisites: ['configuration-profiles-jamf'],
    lessons: [
      { id: 'l1', title: 'FileVault 2 — architecture et clés', duration: '10 min', description: 'XTS-AES-128, PRK, IRK, escrow.' },
      { id: 'l2', title: 'Activation via profil Jamf', duration: '20 min', description: 'Payload FileVault, options, Defer.' },
      { id: 'l3', title: 'Escrow et gestion des clés', duration: '15 min', description: 'Key escrow Jamf, rotation, récupération.' },
      { id: 'l4', title: 'Reporting FileVault', duration: '10 min', description: 'Rapports conformité, smart groups.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 100', 'Jamf 200'],
    order: 3,
  },
  {
    id: 'jamf-gatekeeper',
    slug: 'gatekeeper-xprotect-jamf',
    title: 'Gatekeeper, XProtect et sécurité applicative',
    description: 'Gérer Gatekeeper, XProtect et les mécanismes de sécurité applicative macOS via Jamf Pro pour protéger le parc.',
    moduleId: 'module-4',
    moduleTitle: 'Sécurité Apple avec Jamf',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-05',
    duration: '50 min',
    objectives: [
      'Configurer Gatekeeper via MDM et profils',
      'Comprendre XProtect et ses mises à jour automatiques',
      'Gérer les exceptions Gatekeeper pour les apps internes',
      'Implémenter des contrôles PPPC (Privacy Preferences)',
    ],
    prerequisites: ['jamf-protect-introduction'],
    lessons: [
      { id: 'l1', title: 'Gatekeeper — configuration MDM', duration: '15 min', description: 'Profil Restrictions, assess path, SpCtl.' },
      { id: 'l2', title: 'XProtect et MRT', duration: '10 min', description: 'Malware Removal Tool, mises à jour silencieuses.' },
      { id: 'l3', title: 'PPPC — Privacy Preferences Policy', duration: '15 min', description: 'TCC, profils PPPC, PPPC Utility.' },
      { id: 'l4', title: 'System Extensions et Kernel Extensions', duration: '10 min', description: 'SEXT, KEXT, approbation MDM.' },
    ],
    tools: ['Jamf Pro', 'Jamf Protect', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 4,
  },
  {
    id: 'jamf-cis',
    slug: 'cis-benchmarks-macos',
    title: 'CIS Benchmarks macOS avec Jamf Protect',
    description: 'Implémenter les recommandations CIS Benchmarks macOS et mesurer la conformité du parc via Jamf Protect.',
    moduleId: 'module-4',
    moduleTitle: 'Sécurité Apple avec Jamf',
    level: 'Expert',
    status: 'À jour',
    lastUpdated: '2025-04-20',
    duration: '1h 30min',
    objectives: [
      'Comprendre la structure des CIS Benchmarks macOS',
      'Mapper les contrôles CIS sur les profils Jamf Pro',
      'Configurer les Analytic Baselines CIS dans Jamf Protect',
      'Générer des rapports de conformité CIS pour les audits',
    ],
    prerequisites: ['jamf-protect-introduction', 'gatekeeper-xprotect-jamf'],
    lessons: [
      { id: 'l1', title: 'CIS Benchmarks — structure et niveaux', duration: '20 min', description: 'Level 1, Level 2, scored, not scored.' },
      { id: 'l2', title: 'Mapping CIS → profils Jamf', duration: '30 min', description: 'Correspondance contrôles / payloads.' },
      { id: 'l3', title: 'Jamf Protect CIS Baseline', duration: '25 min', description: 'Configuration, alertes, remédiation.' },
      { id: 'l4', title: 'Rapport d\'audit CIS', duration: '15 min', description: 'Export, scoring, présentation RSSI.' },
    ],
    tools: ['Jamf Protect', 'Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 5,
  },
  {
    id: 'jamf-threat-compliance',
    slug: 'threat-detection-compliance',
    title: 'Détection de menaces et Compliance',
    description: 'Mettre en place une stratégie complète de détection de menaces et de conformité avec Jamf Protect et Jamf Security Cloud.',
    moduleId: 'module-4',
    moduleTitle: 'Sécurité Apple avec Jamf',
    level: 'Expert',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '1h 45min',
    objectives: [
      'Créer des analytics de détection personnalisés dans Jamf Protect',
      'Configurer les alertes et workflows SOAR',
      'Intégrer Jamf Protect avec les SIEM (Splunk, Sentinel)',
      'Construire un programme de conformité continu',
    ],
    prerequisites: ['cis-benchmarks-macos', 'jamf-security-cloud'],
    lessons: [
      { id: 'l1', title: 'Analytics de menaces personnalisés', duration: '30 min', description: 'Unified Logs, ESF, prédicats.' },
      { id: 'l2', title: 'Intégration SIEM', duration: '25 min', description: 'Splunk, Microsoft Sentinel, syslog.' },
      { id: 'l3', title: 'Workflows de réponse aux incidents', duration: '25 min', description: 'Alertes, runbooks, remédiation MDM.' },
      { id: 'l4', title: 'Programme de conformité continu', duration: '25 min', description: 'Métriques, KPI, rapport direction.' },
    ],
    tools: ['Jamf Protect', 'Jamf Security Cloud', 'Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 6,
  },
];

// ─── MODULE 5 — Jamf School ─────────────────────────────────────────────────

const module5Courses: Course[] = [
  {
    id: 'jamf-school-intro',
    slug: 'presentation-jamf-school',
    title: 'Présentation de Jamf School',
    description: 'Découvrir Jamf School, solution MDM dédiée à l\'éducation, et comprendre ses différences avec Jamf Pro.',
    moduleId: 'module-5',
    moduleTitle: 'Jamf School',
    level: 'Débutant',
    status: 'À jour',
    lastUpdated: '2025-02-01',
    duration: '45 min',
    objectives: [
      'Distinguer Jamf School de Jamf Pro',
      'Naviguer dans la console Jamf School',
      'Connecter Jamf School à Apple Business Manager',
      'Comprendre les cas d\'usage éducatif',
    ],
    prerequisites: ['apple-business-manager'],
    lessons: [
      { id: 'l1', title: 'Jamf School vs Jamf Pro', duration: '10 min', description: 'Différences, cas d\'usage, licences.' },
      { id: 'l2', title: 'Configuration initiale', duration: '15 min', description: 'Setup, ABM, APNs, APNS.' },
      { id: 'l3', title: 'Interface et navigation', duration: '10 min', description: 'Dashboard, appareils, utilisateurs, groupes.' },
      { id: 'l4', title: 'Cas d\'usage Education', duration: '10 min', description: 'iPads scolaires, classes, enseignants.' },
    ],
    tools: ['Jamf School', 'Apple Business Manager', 'iPadOS'],
    certificationRelated: [],
    order: 1,
  },
  {
    id: 'jamf-school-ipad',
    slug: 'gestion-ipad-jamf-school',
    title: 'Gestion des iPad avec Jamf School',
    description: 'Enrôler, configurer et gérer des iPad en milieu scolaire via Jamf School avec une approche optimisée pour l\'éducation.',
    moduleId: 'module-5',
    moduleTitle: 'Jamf School',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-02-15',
    duration: '1h',
    objectives: [
      'Enrôler des iPad via ADE dans Jamf School',
      'Créer des profils de configuration iPad',
      'Déployer des applications pédagogiques',
      'Gérer les restrictions et la sécurité',
    ],
    prerequisites: ['presentation-jamf-school'],
    lessons: [
      { id: 'l1', title: 'Enrôlement ADE iPad', duration: '20 min', description: 'PreStage, Setup Assistant, activation.' },
      { id: 'l2', title: 'Profils et restrictions iPad', duration: '20 min', description: 'Configuration profiles, restrictions scolaires.' },
      { id: 'l3', title: 'Déploiement d\'apps pédagogiques', duration: '10 min', description: 'VPP, Managed Apps, apps gratuites.' },
      { id: 'l4', title: 'Gestion du cycle de vie', duration: '10 min', description: 'Wipe, réassignation, mise à jour.' },
    ],
    tools: ['Jamf School', 'Apple Business Manager', 'iPadOS'],
    certificationRelated: [],
    order: 2,
  },
  {
    id: 'jamf-school-classes',
    slug: 'classes-utilisateurs-jamf-school',
    title: 'Classes, enseignants et utilisateurs',
    description: 'Créer et gérer la structure pédagogique dans Jamf School : classes, enseignants, élèves et groupes.',
    moduleId: 'module-5',
    moduleTitle: 'Jamf School',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-01',
    duration: '50 min',
    objectives: [
      'Créer des classes et assigner des enseignants',
      'Importer des utilisateurs depuis un SIS ou CSV',
      'Configurer les droits par rôle',
      'Utiliser l\'app Teacher pour la gestion en classe',
    ],
    prerequisites: ['gestion-ipad-jamf-school'],
    lessons: [
      { id: 'l1', title: 'Structure utilisateurs dans Jamf School', duration: '15 min', description: 'Rôles, groupes, hiérarchie.' },
      { id: 'l2', title: 'Import CSV et SIS', duration: '15 min', description: 'Importation, mapping, synchronisation.' },
      { id: 'l3', title: 'Création et gestion des classes', duration: '10 min', description: 'Classes, liens enseignants/élèves.' },
      { id: 'l4', title: 'App Teacher — gestion en temps réel', duration: '10 min', description: 'Bloom screen, focus, mute, apps.' },
    ],
    tools: ['Jamf School', 'iPadOS'],
    certificationRelated: [],
    order: 3,
  },
  {
    id: 'jamf-school-shared-ipad',
    slug: 'shared-ipad-jamf-school',
    title: 'Shared iPad — iPad partagé',
    description: 'Configurer et gérer le mode Shared iPad pour permettre à plusieurs utilisateurs de partager un même appareil en milieu scolaire.',
    moduleId: 'module-5',
    moduleTitle: 'Jamf School',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-03-10',
    duration: '55 min',
    objectives: [
      'Comprendre l\'architecture Shared iPad',
      'Configurer le Managed Apple Account pour Shared iPad',
      'Paramétrer la taille des quotas utilisateurs',
      'Gérer les transitions entre utilisateurs',
    ],
    prerequisites: ['classes-utilisateurs-jamf-school'],
    lessons: [
      { id: 'l1', title: 'Architecture Shared iPad', duration: '15 min', description: 'Multi-user, APFS volumes, cache.' },
      { id: 'l2', title: 'Configuration dans Jamf School', duration: '20 min', description: 'PreStage, quotas, Managed Apple Accounts.' },
      { id: 'l3', title: 'Expérience utilisateur', duration: '10 min', description: 'Login, données personnelles, déconnexion.' },
      { id: 'l4', title: 'Gestion et maintenance', duration: '10 min', description: 'Purge des comptes, cache, stockage.' },
    ],
    tools: ['Jamf School', 'Apple Business Manager', 'iPadOS'],
    certificationRelated: [],
    order: 4,
  },
  {
    id: 'jamf-school-apps',
    slug: 'apps-pedagogiques-jamf-school',
    title: 'Applications pédagogiques',
    description: 'Sélectionner, acheter et déployer les meilleures applications pédagogiques iOS/iPadOS via Jamf School et Apple Business Manager.',
    moduleId: 'module-5',
    moduleTitle: 'Jamf School',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-15',
    duration: '45 min',
    objectives: [
      'Identifier les apps pédagogiques clés (Pages, Keynote, GarageBand)',
      'Acheter des licences VPP pour les apps éducation',
      'Déployer silencieusement les apps aux classes',
      'Gérer les mises à jour d\'applications',
    ],
    prerequisites: ['gestion-ipad-jamf-school'],
    lessons: [
      { id: 'l1', title: 'Catalogue apps éducation Apple', duration: '10 min', description: 'Creativité, productivité, coding.' },
      { id: 'l2', title: 'Achat VPP et gestion licences', duration: '15 min', description: 'Apps & Books, licences éducation.' },
      { id: 'l3', title: 'Déploiement silencieux par classe', duration: '10 min', description: 'Managed Apps, assignment.' },
      { id: 'l4', title: 'Mises à jour et maintenance', duration: '10 min', description: 'Auto-update, force update, Jamf School.' },
    ],
    tools: ['Jamf School', 'Apple Business Manager', 'iPadOS'],
    certificationRelated: [],
    order: 5,
  },
  {
    id: 'jamf-school-securite',
    slug: 'securite-milieu-scolaire',
    title: 'Sécurité en milieu scolaire',
    description: 'Mettre en place des politiques de sécurité adaptées au milieu scolaire : filtrage web, restrictions et protection des données élèves.',
    moduleId: 'module-5',
    moduleTitle: 'Jamf School',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-03-20',
    duration: '50 min',
    objectives: [
      'Configurer le filtrage de contenu web pour les élèves',
      'Appliquer des restrictions selon le niveau scolaire',
      'Protéger les données personnelles des élèves (RGPD)',
      'Gérer les incidents de sécurité sur les appareils scolaires',
    ],
    prerequisites: ['apps-pedagogiques-jamf-school'],
    lessons: [
      { id: 'l1', title: 'Filtrage web et contenu', duration: '15 min', description: 'Web content filter, catégories, listes.' },
      { id: 'l2', title: 'Restrictions par âge et niveau', duration: '15 min', description: 'Profils de restrictions, Content Ratings.' },
      { id: 'l3', title: 'Protection données élèves (RGPD)', duration: '10 min', description: 'Données collectées, privacy, conformité.' },
      { id: 'l4', title: 'Gestion des incidents', duration: '10 min', description: 'Lost Mode, wipe, actions rapides.' },
    ],
    tools: ['Jamf School', 'Jamf Security Cloud', 'iPadOS'],
    certificationRelated: [],
    order: 6,
  },
];

// ─── MODULE 6 — Jamf Connect ────────────────────────────────────────────────

const module6Courses: Course[] = [
  {
    id: 'jamf-connect-intro',
    slug: 'introduction-jamf-connect',
    title: 'Introduction à Jamf Connect',
    description: 'Comprendre Jamf Connect, son rôle dans l\'authentification cloud pour macOS et son intégration avec les IdP modernes.',
    moduleId: 'module-6',
    moduleTitle: 'Jamf Connect',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-01',
    duration: '1h',
    objectives: [
      'Comprendre la proposition de valeur de Jamf Connect',
      'Identifier les composants : Login Window, Menu Bar, Sync',
      'Connecter Jamf Connect à Microsoft Entra ID',
      'Déployer Jamf Connect via Jamf Pro',
    ],
    prerequisites: ['policies-jamf-pro', 'managed-apple-accounts'],
    lessons: [
      { id: 'l1', title: 'Problématique identité cloud sur macOS', duration: '10 min', description: 'Comptes locaux vs identité cloud, défis.' },
      { id: 'l2', title: 'Architecture Jamf Connect', duration: '20 min', description: 'Login Window, Menu Bar, Sync, OIDC.' },
      { id: 'l3', title: 'Configuration Microsoft Entra ID', duration: '20 min', description: 'App registration, OIDC, scopes, claims.' },
      { id: 'l4', title: 'Déploiement et premiers tests', duration: '10 min', description: 'Package, config profile, test login.' },
    ],
    tools: ['Jamf Connect', 'Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 1,
  },
  {
    id: 'jamf-connect-entra',
    slug: 'jamf-connect-microsoft-entra',
    title: 'Intégration Microsoft Entra ID profonde',
    description: 'Configurer l\'intégration avancée entre Jamf Connect et Microsoft Entra ID : groupes, rôles, Conditional Access et SSPR.',
    moduleId: 'module-6',
    moduleTitle: 'Jamf Connect',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-01',
    duration: '1h 30min',
    objectives: [
      'Mapper les groupes Entra ID aux groupes locaux macOS',
      'Configurer les rôles admin via Entra ID groups',
      'Intégrer Jamf Connect avec Conditional Access',
      'Mettre en place le SSPR (Self-Service Password Reset)',
    ],
    prerequisites: ['introduction-jamf-connect'],
    lessons: [
      { id: 'l1', title: 'Mapping groupes Entra → macOS', duration: '25 min', description: 'Groups, admin mapping, local accounts.' },
      { id: 'l2', title: 'Conditional Access et MFA', duration: '25 min', description: 'CAP, compliant device, token.' },
      { id: 'l3', title: 'SSPR et gestion des mots de passe', duration: '20 min', description: 'Password sync, reset, Kerberos.' },
      { id: 'l4', title: 'Troubleshooting avancé', duration: '20 min', description: 'Logs Jamf Connect, erreurs OIDC, debug.' },
    ],
    tools: ['Jamf Connect', 'Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 2,
  },
  {
    id: 'jamf-connect-sso',
    slug: 'single-sign-on-jamf-connect',
    title: 'Single Sign-On avec Jamf Connect',
    description: 'Configurer le SSO natif macOS via l\'extension Kerberos et Platform SSO pour une expérience utilisateur transparente.',
    moduleId: 'module-6',
    moduleTitle: 'Jamf Connect',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-15',
    duration: '1h 15min',
    objectives: [
      'Configurer l\'extension Kerberos SSO Apple',
      'Déployer Platform SSO (macOS 13+)',
      'Tester le SSO avec les applications Microsoft 365',
      'Déboguer les problèmes d\'authentification SSO',
    ],
    prerequisites: ['jamf-connect-microsoft-entra'],
    lessons: [
      { id: 'l1', title: 'Kerberos SSO Extension Apple', duration: '20 min', description: 'Configuration profile, domains, TGT.' },
      { id: 'l2', title: 'Platform SSO (macOS Ventura+)', duration: '25 min', description: 'Architecture PSSO, Entra ID, provisioning.' },
      { id: 'l3', title: 'SSO Microsoft 365 sur Mac', duration: '20 min', description: 'Tests Teams, Outlook, SharePoint.' },
      { id: 'l4', title: 'Diagnostic SSO', duration: '10 min', description: 'klist, kcpassword, logs, common issues.' },
    ],
    tools: ['Jamf Connect', 'Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 3,
  },
  {
    id: 'jamf-connect-sync',
    slug: 'synchronisation-mots-de-passe',
    title: 'Synchronisation des mots de passe',
    description: 'Maintenir la synchronisation entre le mot de passe cloud (Entra ID) et le mot de passe local macOS via Jamf Connect Sync.',
    moduleId: 'module-6',
    moduleTitle: 'Jamf Connect',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-20',
    duration: '50 min',
    objectives: [
      'Configurer Jamf Connect Sync pour la synchronisation',
      'Gérer les scénarios de changement de mot de passe',
      'Résoudre les désynchronisations de mots de passe',
      'Tester les scénarios offline et online',
    ],
    prerequisites: ['single-sign-on-jamf-connect'],
    lessons: [
      { id: 'l1', title: 'Jamf Connect Sync — architecture', duration: '15 min', description: 'Menu bar app, synchronisation, triggers.' },
      { id: 'l2', title: 'Configuration et déploiement', duration: '15 min', description: 'Config profile Sync, options, branding.' },
      { id: 'l3', title: 'Gestion des scénarios edge cases', duration: '10 min', description: 'Offline, compte local, expiration.' },
      { id: 'l4', title: 'Troubleshooting sync', duration: '10 min', description: 'Logs, diagnostic, résolution.' },
    ],
    tools: ['Jamf Connect', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 4,
  },
  {
    id: 'jamf-connect-zerotrust',
    slug: 'zero-trust-jamf-connect',
    title: 'Zero Trust avec Jamf Connect',
    description: 'Implémenter une stratégie Zero Trust Network Access sur macOS en combinant Jamf Connect, Jamf Pro et Microsoft Entra Conditional Access.',
    moduleId: 'module-6',
    moduleTitle: 'Jamf Connect',
    level: 'Expert',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '1h 30min',
    objectives: [
      'Comprendre les principes Zero Trust appliqués au Mac',
      'Combiner Jamf Pro Compliance + Entra Conditional Access',
      'Configurer le Device Compliance pour macOS',
      'Construire une architecture Zero Trust complète',
    ],
    prerequisites: ['synchronisation-mots-de-passe', 'cis-benchmarks-macos'],
    lessons: [
      { id: 'l1', title: 'Principes Zero Trust sur macOS', duration: '20 min', description: 'Never trust, always verify, posture.' },
      { id: 'l2', title: 'Jamf Pro Compliance Reporting', duration: '25 min', description: 'Compliance token, Entra ID integration.' },
      { id: 'l3', title: 'Conditional Access basé sur la conformité', duration: '25 min', description: 'CAP device compliance, granting/blocking.' },
      { id: 'l4', title: 'Architecture Zero Trust complète', duration: '20 min', description: 'Diagramme, flux, maintenance.' },
    ],
    tools: ['Jamf Connect', 'Jamf Pro', 'Jamf Protect', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 5,
  },
];

// ─── MODULE 7 — Microsoft Intune pour Apple ────────────────────────────────

const module7Courses: Course[] = [
  {
    id: 'intune-apple-intro',
    slug: 'intune-apple-business-manager',
    title: 'Intune et Apple Business Manager',
    description: 'Connecter Microsoft Intune à Apple Business Manager pour gérer les appareils Apple dans l\'écosystème Microsoft 365.',
    moduleId: 'module-7',
    moduleTitle: 'Microsoft Intune pour Apple',
    level: 'Débutant',
    status: 'À jour',
    lastUpdated: '2025-03-15',
    duration: '1h',
    objectives: [
      'Configurer la connexion Intune ↔ Apple Business Manager',
      'Créer un Apple MDM Push Certificate dans Intune',
      'Comprendre le portail Intune (Endpoint Manager)',
      'Distinguer Intune de Jamf Pro pour la gestion Apple',
    ],
    prerequisites: ['apple-business-manager', 'automated-device-enrollment'],
    lessons: [
      { id: 'l1', title: 'Microsoft Intune — présentation', duration: '15 min', description: 'Endpoint Manager, licences, positionnement.' },
      { id: 'l2', title: 'Apple MDM Push Certificate', duration: '15 min', description: 'Génération, upload Intune, renouvellement.' },
      { id: 'l3', title: 'Connexion ABM ↔ Intune', duration: '20 min', description: 'Token ABM, MDM Server, synchronisation.' },
      { id: 'l4', title: 'Navigation portail Intune (Apple)', duration: '10 min', description: 'Devices, Policies, Apps, Reports.' },
    ],
    tools: ['Microsoft Intune', 'Apple Business Manager', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Microsoft MD-102'],
    order: 1,
  },
  {
    id: 'intune-ade',
    slug: 'enrolement-ade-intune',
    title: 'Enrôlement ADE avec Microsoft Intune',
    description: 'Configurer et tester l\'enrôlement automatique d\'appareils Apple (ADE) via Microsoft Intune pour macOS et iOS.',
    moduleId: 'module-7',
    moduleTitle: 'Microsoft Intune pour Apple',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-25',
    duration: '1h 15min',
    objectives: [
      'Créer des profils d\'enrôlement ADE macOS et iOS dans Intune',
      'Configurer l\'Assistant de configuration macOS',
      'Assigner les profils dans ABM',
      'Valider un enrôlement ADE de bout en bout',
    ],
    prerequisites: ['intune-apple-business-manager'],
    lessons: [
      { id: 'l1', title: 'Enrollment Program Token Intune', duration: '15 min', description: 'Token ABM, synchronisation, gestion.' },
      { id: 'l2', title: 'Profil ADE macOS', duration: '25 min', description: 'Setup Assistant, MDM activation, options.' },
      { id: 'l3', title: 'Profil ADE iOS/iPadOS', duration: '20 min', description: 'iPhone, iPad, options spécifiques.' },
      { id: 'l4', title: 'Test et validation', duration: '15 min', description: 'Workflow complet, vérification Intune.' },
    ],
    tools: ['Microsoft Intune', 'Apple Business Manager', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Microsoft MD-102'],
    order: 2,
  },
  {
    id: 'intune-macos',
    slug: 'gestion-macos-intune',
    title: 'Gestion macOS avec Microsoft Intune',
    description: 'Administrer les Mac via Intune : profils de configuration, compliance, scripts et mises à jour macOS.',
    moduleId: 'module-7',
    moduleTitle: 'Microsoft Intune pour Apple',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-04-05',
    duration: '1h 30min',
    objectives: [
      'Créer des profils de configuration macOS dans Intune',
      'Déployer des scripts Bash via Intune',
      'Configurer les politiques de mise à jour macOS',
      'Gérer les applications macOS (PKG, DMG, Microsoft 365)',
    ],
    prerequisites: ['enrolement-ade-intune'],
    lessons: [
      { id: 'l1', title: 'Profils de configuration macOS Intune', duration: '25 min', description: 'Settings Catalog, templates, custom PLIST.' },
      { id: 'l2', title: 'Scripts Shell dans Intune', duration: '25 min', description: 'Shell scripts, fréquence, contexte.' },
      { id: 'l3', title: 'Déploiement d\'applications macOS', duration: '25 min', description: 'PKG, DMG, LOB apps, M365.' },
      { id: 'l4', title: 'Software Updates macOS', duration: '15 min', description: 'DDM Intune, Managed Updates, policies.' },
    ],
    tools: ['Microsoft Intune', 'macOS'],
    certificationRelated: ['Microsoft MD-102'],
    order: 3,
  },
  {
    id: 'intune-ios',
    slug: 'gestion-iphone-ipad-intune',
    title: 'Gestion iPhone et iPad avec Intune',
    description: 'Gérer les appareils iOS et iPadOS via Microsoft Intune : profils, applications, compliance et actions à distance.',
    moduleId: 'module-7',
    moduleTitle: 'Microsoft Intune pour Apple',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-04-10',
    duration: '1h 20min',
    objectives: [
      'Configurer des profils de restriction iOS dans Intune',
      'Déployer des applications iOS via Intune',
      'Configurer l\'accès email et VPN sur iPhone',
      'Effectuer des actions à distance (wipe, sync, lock)',
    ],
    prerequisites: ['enrolement-ade-intune'],
    lessons: [
      { id: 'l1', title: 'Profils de configuration iOS/iPadOS', duration: '25 min', description: 'Restrictions, Wi-Fi, VPN, certificats.' },
      { id: 'l2', title: 'Déploiement d\'apps iOS', duration: '20 min', description: 'VPP apps, LOB apps, web links.' },
      { id: 'l3', title: 'Email et Office 365 sur iPhone', duration: '20 min', description: 'Exchange, Outlook, MAM policies.' },
      { id: 'l4', title: 'Actions à distance et maintenance', duration: '15 min', description: 'Remote lock, wipe, sync, rename.' },
    ],
    tools: ['Microsoft Intune', 'Apple Business Manager', 'iOS', 'iPadOS'],
    certificationRelated: ['Microsoft MD-102'],
    order: 4,
  },
  {
    id: 'intune-compliance',
    slug: 'compliance-policies-intune-apple',
    title: 'Compliance Policies pour appareils Apple',
    description: 'Créer et gérer des politiques de conformité Intune pour les Mac et appareils iOS afin d\'évaluer leur état de sécurité.',
    moduleId: 'module-7',
    moduleTitle: 'Microsoft Intune pour Apple',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-20',
    duration: '1h',
    objectives: [
      'Créer des Compliance Policies macOS et iOS',
      'Définir les critères de conformité (chiffrement, OS, PIN)',
      'Configurer les actions en cas de non-conformité',
      'Visualiser les rapports de conformité',
    ],
    prerequisites: ['gestion-macos-intune', 'gestion-iphone-ipad-intune'],
    lessons: [
      { id: 'l1', title: 'Compliance Policies — concept', duration: '10 min', description: 'Conformité, marquage, actions.' },
      { id: 'l2', title: 'Critères macOS et iOS', duration: '25 min', description: 'OS version, chiffrement, MDM, jailbreak.' },
      { id: 'l3', title: 'Actions on noncompliance', duration: '15 min', description: 'Email, notification, retire, remotely lock.' },
      { id: 'l4', title: 'Rapports de conformité', duration: '10 min', description: 'Device compliance dashboard, export.' },
    ],
    tools: ['Microsoft Intune', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Microsoft MD-102'],
    order: 5,
  },
  {
    id: 'intune-conditional-access',
    slug: 'conditional-access-apple-intune',
    title: 'Conditional Access pour appareils Apple',
    description: 'Configurer l\'accès conditionnel Microsoft Entra ID pour les Mac et appareils iOS gérés par Intune.',
    moduleId: 'module-7',
    moduleTitle: 'Microsoft Intune pour Apple',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '1h 15min',
    objectives: [
      'Créer des politiques d\'accès conditionnel pour Apple',
      'Exiger la conformité Intune pour accéder aux ressources M365',
      'Configurer le MFA et la session sur les Mac',
      'Tester et monitorer les politiques CAP',
    ],
    prerequisites: ['compliance-policies-intune-apple'],
    lessons: [
      { id: 'l1', title: 'Conditional Access — architecture', duration: '15 min', description: 'Signals, decisions, enforcement.' },
      { id: 'l2', title: 'CAP pour Mac — require compliant device', duration: '25 min', description: 'Policy, test, monitoring.' },
      { id: 'l3', title: 'CAP pour iOS — Approved app / MAM', duration: '20 min', description: 'Approved client apps, app protection.' },
      { id: 'l4', title: 'Named Locations et exclusions', duration: '15 min', description: 'IP, pays, break-glass accounts.' },
    ],
    tools: ['Microsoft Intune', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Microsoft MD-102', 'Microsoft MS-102'],
    order: 6,
  },
  {
    id: 'intune-defender',
    slug: 'microsoft-defender-apple',
    title: 'Microsoft Defender for Endpoint sur Apple',
    description: 'Déployer et configurer Microsoft Defender for Endpoint sur macOS et iOS pour la protection avancée contre les menaces.',
    moduleId: 'module-7',
    moduleTitle: 'Microsoft Intune pour Apple',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-05-05',
    duration: '1h 20min',
    objectives: [
      'Déployer MDE sur macOS via Intune',
      'Configurer l\'onboarding et les paramètres de base',
      'Intégrer MDE avec Microsoft Defender XDR',
      'Analyser les alertes et incidents MDE',
    ],
    prerequisites: ['conditional-access-apple-intune'],
    lessons: [
      { id: 'l1', title: 'Microsoft Defender for Endpoint — macOS', duration: '25 min', description: 'Déploiement, onboarding, configuration.' },
      { id: 'l2', title: 'MDE sur iOS', duration: '20 min', description: 'App Intune, permissions, phishing protection.' },
      { id: 'l3', title: 'Intégration Microsoft Defender XDR', duration: '20 min', description: 'Portal, incidents, alertes, remediation.' },
      { id: 'l4', title: 'Reporting et hunting', duration: '15 min', description: 'Advanced Hunting KQL, rapports sécurité.' },
    ],
    tools: ['Microsoft Intune', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Microsoft MD-102', 'Microsoft MS-102'],
    order: 7,
  },
  {
    id: 'intune-profiles',
    slug: 'profils-configuration-intune-apple',
    title: 'Profils de configuration avancés Intune',
    description: 'Maîtriser la création de profils de configuration avancés pour Apple via le Settings Catalog et les profils personnalisés PLIST.',
    moduleId: 'module-7',
    moduleTitle: 'Microsoft Intune pour Apple',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-25',
    duration: '1h 10min',
    objectives: [
      'Utiliser le Settings Catalog pour macOS et iOS',
      'Créer des profils personnalisés avec PLIST/XML',
      'Déployer des certificats et des profils SCEP',
      'Résoudre les conflits entre profils',
    ],
    prerequisites: ['gestion-macos-intune', 'gestion-iphone-ipad-intune'],
    lessons: [
      { id: 'l1', title: 'Settings Catalog — navigation avancée', duration: '20 min', description: 'Recherche, catégories, nouvelles settings.' },
      { id: 'l2', title: 'Profils personnalisés PLIST', duration: '20 min', description: 'Custom profiles, XML, débogage.' },
      { id: 'l3', title: 'Certificats et SCEP dans Intune', duration: '20 min', description: 'SCEP, PKCS, trusted root, NDES.' },
      { id: 'l4', title: 'Gestion des conflits de profils', duration: '10 min', description: 'Précédence, résolution, rapport.' },
    ],
    tools: ['Microsoft Intune', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Microsoft MD-102'],
    order: 8,
  },
];

// ─── MODULE 8 — Android Enterprise avec Intune ─────────────────────────────

const module8Courses: Course[] = [
  {
    id: 'android-intro',
    slug: 'introduction-android-enterprise',
    title: 'Introduction à Android Enterprise',
    description: 'Comprendre le programme Android Enterprise de Google et ses modes de gestion pour les déploiements en entreprise.',
    moduleId: 'module-8',
    moduleTitle: 'Android Enterprise avec Intune',
    level: 'Débutant',
    status: 'À jour',
    lastUpdated: '2025-03-01',
    duration: '50 min',
    objectives: [
      'Comprendre l\'évolution de Android for Work vers Android Enterprise',
      'Identifier les modes de gestion AE disponibles',
      'Connecter un tenant Intune à Google Play Managed',
      'Distinguer les cas d\'usage de chaque mode',
    ],
    prerequisites: ['intune-apple-business-manager'],
    lessons: [
      { id: 'l1', title: 'Historique Android Enterprise', duration: '10 min', description: 'Android for Work, évolution, Google.' },
      { id: 'l2', title: 'Modes de gestion AE', duration: '15 min', description: 'Work Profile, Fully Managed, Dedicated, COPE.' },
      { id: 'l3', title: 'Connexion Intune ↔ Google Play', duration: '15 min', description: 'Managed Google Play, binding, apps.' },
      { id: 'l4', title: 'Choix du mode adapté', duration: '10 min', description: 'BYOD, COBO, COSU, COPE — guide décision.' },
    ],
    tools: ['Android Enterprise', 'Microsoft Intune'],
    certificationRelated: ['Microsoft MD-102'],
    order: 1,
  },
  {
    id: 'android-work-profile',
    slug: 'android-work-profile',
    title: 'Android Work Profile (BYOD)',
    description: 'Configurer et gérer le mode Work Profile Android pour les appareils personnels (BYOD) avec séparation vie pro/perso.',
    moduleId: 'module-8',
    moduleTitle: 'Android Enterprise avec Intune',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-15',
    duration: '1h',
    objectives: [
      'Créer un profil d\'enrôlement Work Profile dans Intune',
      'Comprendre la séparation des données pro/perso',
      'Déployer des applications dans le Work Profile',
      'Configurer les politiques de conformité Work Profile',
    ],
    prerequisites: ['introduction-android-enterprise'],
    lessons: [
      { id: 'l1', title: 'Architecture Work Profile', duration: '15 min', description: 'Conteneur, chiffrement, séparation.' },
      { id: 'l2', title: 'Enrôlement Work Profile via Intune', duration: '20 min', description: 'Company Portal, QR, NFC, profil.' },
      { id: 'l3', title: 'Apps et configuration Work Profile', duration: '15 min', description: 'Managed Google Play, déploiement, config.' },
      { id: 'l4', title: 'Compliance et restrictions Work Profile', duration: '10 min', description: 'Compliance policies, copy-paste restrictions.' },
    ],
    tools: ['Android Enterprise', 'Microsoft Intune'],
    certificationRelated: ['Microsoft MD-102'],
    order: 2,
  },
  {
    id: 'android-fully-managed',
    slug: 'android-fully-managed',
    title: 'Android Fully Managed Devices (COBO)',
    description: 'Déployer et gérer des appareils Android d\'entreprise en mode Fully Managed (COBO) avec contrôle total via Intune.',
    moduleId: 'module-8',
    moduleTitle: 'Android Enterprise avec Intune',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-03-20',
    duration: '1h 10min',
    objectives: [
      'Configurer l\'enrôlement Fully Managed (COBO)',
      'Utiliser le Zero-Touch Enrollment Android',
      'Gérer l\'ensemble du système depuis Intune',
      'Appliquer des restrictions complètes de l\'appareil',
    ],
    prerequisites: ['introduction-android-enterprise'],
    lessons: [
      { id: 'l1', title: 'Fully Managed — architecture', duration: '15 min', description: 'COBO, propriété entreprise, contrôle total.' },
      { id: 'l2', title: 'Méthodes d\'enrôlement COBO', duration: '25 min', description: 'QR Code, Zero-Touch, NFC, Token DPC.' },
      { id: 'l3', title: 'Configuration et restrictions système', duration: '20 min', description: 'Profiles, System Update Policy, restrictions.' },
      { id: 'l4', title: 'Zero-Touch Enrollment Android', duration: '10 min', description: 'Customer portail ZT, config JSON, déploiement.' },
    ],
    tools: ['Android Enterprise', 'Microsoft Intune'],
    certificationRelated: ['Microsoft MD-102'],
    order: 3,
  },
  {
    id: 'android-cope',
    slug: 'android-cope',
    title: 'Android COPE — Corporate Owned Personally Enabled',
    description: 'Implémenter le mode COPE Android pour des appareils d\'entreprise offrant une utilisation personnelle contrôlée.',
    moduleId: 'module-8',
    moduleTitle: 'Android Enterprise avec Intune',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-05',
    duration: '55 min',
    objectives: [
      'Comprendre les différences COPE vs Work Profile vs Fully Managed',
      'Configurer l\'enrôlement COPE dans Intune',
      'Gérer le profil de travail et le profil personnel en COPE',
      'Appliquer des restrictions adaptées au mode COPE',
    ],
    prerequisites: ['android-fully-managed'],
    lessons: [
      { id: 'l1', title: 'COPE — concept et architecture', duration: '15 min', description: 'Appareils d\'entreprise + usage personnel.' },
      { id: 'l2', title: 'Enrôlement COPE dans Intune', duration: '20 min', description: 'Profile, Zero-Touch, configuration.' },
      { id: 'l3', title: 'Gestion du profil de travail COPE', duration: '10 min', description: 'Apps, restrictions, données d\'entreprise.' },
      { id: 'l4', title: 'Restrictions et politique COPE', duration: '10 min', description: 'Personal profile limits, screen capture.' },
    ],
    tools: ['Android Enterprise', 'Microsoft Intune'],
    certificationRelated: ['Microsoft MD-102'],
    order: 4,
  },
  {
    id: 'android-dedicated',
    slug: 'android-dedicated-devices',
    title: 'Android Dedicated Devices (COSU)',
    description: 'Déployer des appareils Android en mode kiosque (COSU) pour des usages à usage unique ou multi-apps contrôlés.',
    moduleId: 'module-8',
    moduleTitle: 'Android Enterprise avec Intune',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-10',
    duration: '1h',
    objectives: [
      'Configurer le mode kiosque Android (COSU)',
      'Déployer en mode Single App Kiosk',
      'Configurer le Multi-App Kiosk',
      'Gérer les appareils kiosque à distance',
    ],
    prerequisites: ['android-cope'],
    lessons: [
      { id: 'l1', title: 'COSU — Corporate Owned Single Use', duration: '10 min', description: 'Kiosques, terminaux, usage unique.' },
      { id: 'l2', title: 'Single App Kiosk', duration: '20 min', description: 'Une seule app, locked mode, config.' },
      { id: 'l3', title: 'Multi-App Kiosk', duration: '20 min', description: 'Managed Home Screen, apps autorisées.' },
      { id: 'l4', title: 'Gestion à distance des kiosques', duration: '10 min', description: 'Actions, diagnostics, mise à jour.' },
    ],
    tools: ['Android Enterprise', 'Microsoft Intune'],
    certificationRelated: ['Microsoft MD-102'],
    order: 5,
  },
  {
    id: 'android-apps',
    slug: 'deploiement-apps-android',
    title: 'Déploiement d\'applications Android',
    description: 'Déployer, configurer et gérer les applications Android via Managed Google Play et Microsoft Intune.',
    moduleId: 'module-8',
    moduleTitle: 'Android Enterprise avec Intune',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-04-15',
    duration: '1h',
    objectives: [
      'Approuver et synchroniser des apps depuis Managed Google Play',
      'Déployer des apps en Required, Available ou Uninstall',
      'Configurer les App Configuration Policies Android',
      'Gérer les apps privées (Private Apps)',
    ],
    prerequisites: ['introduction-android-enterprise'],
    lessons: [
      { id: 'l1', title: 'Managed Google Play — navigation', duration: '15 min', description: 'Approval, sync, apps disponibles.' },
      { id: 'l2', title: 'Déploiement Required / Available', duration: '20 min', description: 'Assignation, groupes, modes.' },
      { id: 'l3', title: 'App Configuration Policies', duration: '15 min', description: 'Managed Config, JSON, prérempli.' },
      { id: 'l4', title: 'Private Apps et APK', duration: '10 min', description: 'Upload, gestion, mises à jour.' },
    ],
    tools: ['Android Enterprise', 'Microsoft Intune'],
    certificationRelated: ['Microsoft MD-102'],
    order: 6,
  },
  {
    id: 'android-compliance',
    slug: 'politiques-conformite-android',
    title: 'Politiques de conformité Android',
    description: 'Créer des politiques de conformité Android dans Intune pour évaluer l\'état de sécurité des appareils et restreindre les accès.',
    moduleId: 'module-8',
    moduleTitle: 'Android Enterprise avec Intune',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-04-20',
    duration: '55 min',
    objectives: [
      'Créer des Compliance Policies Android Enterprise',
      'Configurer les critères de conformité adaptés',
      'Lier les Compliance Policies au Conditional Access',
      'Analyser les rapports de conformité Android',
    ],
    prerequisites: ['android-work-profile', 'android-fully-managed'],
    lessons: [
      { id: 'l1', title: 'Compliance Policies Android — critères', duration: '20 min', description: 'OS version, chiffrement, root, PIN, attestation.' },
      { id: 'l2', title: 'Actions on noncompliance', duration: '15 min', description: 'Notifications, blocage, wipe, délais.' },
      { id: 'l3', title: 'CAP et conformité Android', duration: '10 min', description: 'Conditional Access, Azure AD join.' },
      { id: 'l4', title: 'Rapports et monitoring', duration: '10 min', description: 'Dashboard, per-policy, per-device.' },
    ],
    tools: ['Android Enterprise', 'Microsoft Intune'],
    certificationRelated: ['Microsoft MD-102'],
    order: 7,
  },
  {
    id: 'android-securite',
    slug: 'securite-android-intune',
    title: 'Sécurité Android avec Microsoft Intune',
    description: 'Mettre en place une stratégie de sécurité complète pour les appareils Android avec Intune, MDE et App Protection Policies.',
    moduleId: 'module-8',
    moduleTitle: 'Android Enterprise avec Intune',
    level: 'Expert',
    status: 'À jour',
    lastUpdated: '2025-05-05',
    duration: '1h 30min',
    objectives: [
      'Déployer Microsoft Defender for Endpoint sur Android',
      'Configurer les App Protection Policies (MAM)',
      'Mettre en place le Mobile Threat Defense Android',
      'Construire une stratégie sécurité Android complète',
    ],
    prerequisites: ['politiques-conformite-android', 'microsoft-defender-apple'],
    lessons: [
      { id: 'l1', title: 'MDE sur Android', duration: '25 min', description: 'Déploiement, permissions, antivirus, réseau.' },
      { id: 'l2', title: 'App Protection Policies (MAM)', duration: '25 min', description: 'Sans enrôlement, sans enrôlement, données.' },
      { id: 'l3', title: 'Mobile Threat Defense Android', duration: '20 min', description: 'MTD connector, niveaux de risque, CAP.' },
      { id: 'l4', title: 'Stratégie sécurité Android globale', duration: '20 min', description: 'Architecture, documentation, maintenance.' },
    ],
    tools: ['Android Enterprise', 'Microsoft Intune'],
    certificationRelated: ['Microsoft MD-102'],
    order: 8,
  },
];

// ─── MODULE 9 — Certifications ──────────────────────────────────────────────

const module9Courses: Course[] = [
  {
    id: 'cert-apple-device-support',
    slug: 'certification-apple-device-support',
    title: 'Apple Certified Support Professional',
    description: 'Préparer la certification Apple Device Support pour valider vos compétences en support et administration des appareils Apple.',
    moduleId: 'module-9',
    moduleTitle: 'Certifications',
    level: 'Intermédiaire',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '2h',
    objectives: [
      'Connaître le périmètre de l\'examen Apple Device Support',
      'Maîtriser les thèmes clés : macOS, iOS, iCloud, sécurité',
      'S\'entraîner avec des questions types',
      'Savoir s\'inscrire et passer l\'examen Pearson VUE',
    ],
    prerequisites: ['ecosysteme-apple-entreprise', 'securite-conformite-apple'],
    lessons: [
      { id: 'l1', title: 'Présentation de la certification', duration: '20 min', description: 'Objectifs, format, inscription, coût.' },
      { id: 'l2', title: 'Domaines de compétences clés', duration: '40 min', description: 'macOS, iOS, troubleshooting, sécurité.' },
      { id: 'l3', title: 'Questions d\'entraînement', duration: '40 min', description: 'Pratique, analyse des réponses, révision.' },
      { id: 'l4', title: 'Stratégie d\'examen', duration: '20 min', description: 'Temps, méthode, gestion du stress.' },
    ],
    tools: ['macOS', 'iOS', 'iPadOS', 'Apple Business Manager'],
    certificationRelated: ['Apple Device Support'],
    order: 1,
  },
  {
    id: 'cert-apple-deployment',
    slug: 'certification-apple-deployment',
    title: 'Apple Deployment and Management',
    description: 'Préparer la certification Apple Deployment and Management pour valider vos compétences en déploiement et gestion MDM Apple.',
    moduleId: 'module-9',
    moduleTitle: 'Certifications',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '2h 30min',
    objectives: [
      'Maîtriser le périmètre Deployment and Management Apple',
      'Réviser ABM, ADE, MDM, Apps & Books',
      'Pratiquer les questions sur la gestion MDM',
      'Planifier son passage d\'examen',
    ],
    prerequisites: ['automated-device-enrollment', 'configuration-profiles-jamf'],
    lessons: [
      { id: 'l1', title: 'Structure de la certification', duration: '20 min', description: 'Format, durée, domaines, passing score.' },
      { id: 'l2', title: 'Révision ABM et ADE', duration: '40 min', description: 'Récapitulatif ABM, ADE, profils.' },
      { id: 'l3', title: 'Révision MDM et configuration', duration: '40 min', description: 'Profils, apps, compliance, gestion.' },
      { id: 'l4', title: 'Entraînement final', duration: '50 min', description: 'Questions types, correction, conseils.' },
    ],
    tools: ['Apple Business Manager', 'macOS', 'iOS', 'iPadOS'],
    certificationRelated: ['Apple Deployment and Management'],
    order: 2,
  },
  {
    id: 'cert-jamf-100',
    slug: 'certification-jamf-100',
    title: 'Jamf Certified Tech (Jamf 100)',
    description: 'Préparer l\'examen Jamf 100 pour obtenir la certification Jamf Certified Tech et valider les fondamentaux Jamf Pro.',
    moduleId: 'module-9',
    moduleTitle: 'Certifications',
    level: 'Débutant',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '2h',
    objectives: [
      'Connaître le format et les domaines du Jamf 100',
      'Réviser les concepts fondamentaux Jamf Pro',
      'S\'entraîner sur les scénarios d\'administration de base',
      'Planifier son passage via Pearson VUE',
    ],
    prerequisites: ['introduction-jamf-pro'],
    lessons: [
      { id: 'l1', title: 'Présentation de la certification Jamf 100', duration: '20 min', description: 'Objectifs, format, coût, inscription.' },
      { id: 'l2', title: 'Révision fondamentaux Jamf Pro', duration: '40 min', description: 'Enrôlement, profils, policies, Smart Groups.' },
      { id: 'l3', title: 'Scénarios pratiques Jamf 100', duration: '40 min', description: 'Questions situationnelles, analyse.' },
      { id: 'l4', title: 'Conseils de passage', duration: '20 min', description: 'Stratégie, gestion du temps, révision finale.' },
    ],
    tools: ['Jamf Pro', 'Apple Business Manager', 'macOS'],
    certificationRelated: ['Jamf 100'],
    order: 3,
  },
  {
    id: 'cert-jamf-170',
    slug: 'certification-jamf-170',
    title: 'Jamf Certified Admin (Jamf 170)',
    description: 'Préparer le Jamf 170 pour la certification Jamf Certified Admin : scripting, API, automatisation et gestion avancée.',
    moduleId: 'module-9',
    moduleTitle: 'Certifications',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '2h 30min',
    objectives: [
      'Maîtriser les domaines avancés du Jamf 170',
      'Réviser scripting Bash, API Jamf, packaging',
      'Pratiquer les scénarios d\'automatisation',
      'Se préparer aux questions sur les workflows complexes',
    ],
    prerequisites: ['certification-jamf-100', 'scripting-bash-jamf'],
    lessons: [
      { id: 'l1', title: 'Structure du Jamf 170', duration: '20 min', description: 'Domaines, niveau, format, passing score.' },
      { id: 'l2', title: 'Révision scripting et packaging', duration: '50 min', description: 'Bash avancé, PKG, Composer, API.' },
      { id: 'l3', title: 'Scénarios d\'automatisation avancés', duration: '50 min', description: 'Zero-Touch, API, remédiation.' },
      { id: 'l4', title: 'Préparation finale Jamf 170', duration: '30 min', description: 'Questions types, stratégie, dernière révision.' },
    ],
    tools: ['Jamf Pro', 'macOS'],
    certificationRelated: ['Jamf 170'],
    order: 4,
  },
  {
    id: 'cert-jamf-200',
    slug: 'certification-jamf-200',
    title: 'Jamf Certified Expert (Jamf 200)',
    description: 'Préparer le Jamf 200 pour atteindre le niveau Jamf Certified Expert : architecture, sécurité, Zero Trust et projets complexes.',
    moduleId: 'module-9',
    moduleTitle: 'Certifications',
    level: 'Expert',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '3h',
    objectives: [
      'Maîtriser l\'architecture complète Jamf Pro',
      'Réviser Jamf Protect, Jamf Connect et la sécurité',
      'Préparer les questions de niveau Expert',
      'Construire un portfolio de projets Jamf',
    ],
    prerequisites: ['certification-jamf-170', 'zero-trust-jamf-connect'],
    lessons: [
      { id: 'l1', title: 'Présentation du Jamf 200', duration: '20 min', description: 'Niveau expert, domaines, examen.' },
      { id: 'l2', title: 'Révision architecture et sécurité', duration: '60 min', description: 'Jamf Protect, Connect, Zero Trust, API.' },
      { id: 'l3', title: 'Projets et cas réels', duration: '60 min', description: 'Scénarios enterprise, solutions proposées.' },
      { id: 'l4', title: 'Préparation examen Jamf 200', duration: '40 min', description: 'Questions avancées, méthode, conseils.' },
      { id: 'l5', title: 'Portfolio professionnel Jamf', duration: '20 min', description: 'CV, LinkedIn, projets GitHub.' },
    ],
    tools: ['Jamf Pro', 'Jamf Protect', 'Jamf Connect', 'Jamf Security Cloud', 'macOS'],
    certificationRelated: ['Jamf 200'],
    order: 5,
  },
  {
    id: 'cert-md102',
    slug: 'certification-md-102',
    title: 'Microsoft MD-102 — Endpoint Administrator',
    description: 'Préparer l\'examen Microsoft MD-102 pour la certification Microsoft 365 Certified: Endpoint Administrator Associate.',
    moduleId: 'module-9',
    moduleTitle: 'Certifications',
    level: 'Avancé',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '3h',
    objectives: [
      'Connaître le périmètre complet de l\'examen MD-102',
      'Réviser Intune, Autopilot, SCCM, Windows et Apple',
      'Pratiquer les questions sur les scénarios Endpoint',
      'Planifier l\'examen via Pearson VUE',
    ],
    prerequisites: ['conditional-access-apple-intune', 'politiques-conformite-android'],
    lessons: [
      { id: 'l1', title: 'Structure MD-102', duration: '20 min', description: 'Objectifs, format, domaines, passing score.' },
      { id: 'l2', title: 'Révision Intune et gestion Apple/Android', duration: '60 min', description: 'MDM, MAM, compliance, CAP.' },
      { id: 'l3', title: 'Scénarios d\'examen MD-102', duration: '60 min', description: 'Questions types, analyse, correction.' },
      { id: 'l4', title: 'Stratégie et passage de l\'examen', duration: '40 min', description: 'Gestion du temps, passages difficiles.' },
      { id: 'l5', title: 'Ressources complémentaires', duration: '20 min', description: 'Microsoft Learn, labs, sandbox.' },
    ],
    tools: ['Microsoft Intune', 'macOS', 'iOS', 'iPadOS', 'Android Enterprise'],
    certificationRelated: ['Microsoft MD-102'],
    order: 6,
  },
  {
    id: 'cert-ms102',
    slug: 'certification-ms-102',
    title: 'Microsoft MS-102 — Enterprise Administrator',
    description: 'Préparer l\'examen MS-102 pour la certification Microsoft 365 Certified: Enterprise Administrator Expert.',
    moduleId: 'module-9',
    moduleTitle: 'Certifications',
    level: 'Expert',
    status: 'À jour',
    lastUpdated: '2025-05-01',
    duration: '3h',
    objectives: [
      'Maîtriser le périmètre Microsoft 365 Enterprise Administration',
      'Réviser la sécurité M365, Defender, Entra ID',
      'Préparer les scénarios d\'administration avancée',
      'Viser la certification Expert Microsoft',
    ],
    prerequisites: ['certification-md-102'],
    lessons: [
      { id: 'l1', title: 'Structure MS-102', duration: '20 min', description: 'Prérequis, format, domaines expert.' },
      { id: 'l2', title: 'Révision sécurité M365', duration: '60 min', description: 'Defender, Purview, Entra, Compliance.' },
      { id: 'l3', title: 'Administration avancée M365', duration: '60 min', description: 'Tenant, identité, gouvernance, Teams.' },
      { id: 'l4', title: 'Entraînement final MS-102', duration: '60 min', description: 'Questions expert, cas complexes.' },
    ],
    tools: ['Microsoft Intune'],
    certificationRelated: ['Microsoft MS-102'],
    order: 7,
  },
];

// ─── MODULES ASSEMBLY ──────────────────────────────────────────────────────

export const MODULES: Module[] = [
  {
    id: 'module-1',
    slug: 'fondations-apple-enterprise',
    title: 'Fondations Apple Enterprise',
    description: 'Maîtrisez l\'écosystème Apple en entreprise : Apple Business Manager, Managed Apple Accounts, Apps & Books et Automated Device Enrollment.',
    icon: '🍎',
    color: 'blue',
    order: 1,
    courses: module1Courses,
  },
  {
    id: 'module-2',
    slug: 'administration-macos-jamf-pro',
    title: 'Administration macOS avec Jamf Pro',
    description: 'Devenez expert Jamf Pro pour la gestion des Mac : enrôlement, profils, policies, Smart Groups, Self Service et patch management.',
    icon: '🖥️',
    color: 'orange',
    order: 2,
    courses: module2Courses,
  },
  {
    id: 'module-3',
    slug: 'automatisation-jamf-pro',
    title: 'Automatisation Jamf Pro',
    description: 'Automatisez les opérations Jamf Pro : API, scripting Bash, packaging, workflows Zero-Touch et remédiation automatique.',
    icon: '⚙️',
    color: 'purple',
    order: 3,
    courses: module3Courses,
  },
  {
    id: 'module-4',
    slug: 'securite-apple-jamf',
    title: 'Sécurité Apple avec Jamf',
    description: 'Protégez votre parc Apple avec Jamf Protect, Jamf Security Cloud, FileVault, Gatekeeper et les CIS Benchmarks macOS.',
    icon: '🛡️',
    color: 'red',
    order: 4,
    courses: module4Courses,
  },
  {
    id: 'module-5',
    slug: 'jamf-school',
    title: 'Jamf School',
    description: 'Gérez les appareils éducatifs avec Jamf School : iPad, classes, Shared iPad, applications pédagogiques et sécurité scolaire.',
    icon: '🎓',
    color: 'green',
    order: 5,
    courses: module5Courses,
  },
  {
    id: 'module-6',
    slug: 'jamf-connect',
    title: 'Jamf Connect',
    description: 'Unifiez l\'identité cloud sur macOS avec Jamf Connect : Microsoft Entra ID, SSO, synchronisation des mots de passe et Zero Trust.',
    icon: '🔐',
    color: 'indigo',
    order: 6,
    courses: module6Courses,
  },
  {
    id: 'module-7',
    slug: 'microsoft-intune-apple',
    title: 'Microsoft Intune pour Apple',
    description: 'Gérez les Mac, iPhone et iPad avec Microsoft Intune : ADE, profils, compliance, Conditional Access et Microsoft Defender.',
    icon: '🪟',
    color: 'cyan',
    order: 7,
    courses: module7Courses,
  },
  {
    id: 'module-8',
    slug: 'android-enterprise-intune',
    title: 'Android Enterprise avec Intune',
    description: 'Déployez et gérez les appareils Android en entreprise avec Intune : Work Profile, Fully Managed, COPE, applications et sécurité.',
    icon: '🤖',
    color: 'emerald',
    order: 8,
    courses: module8Courses,
  },
  {
    id: 'module-9',
    slug: 'certifications',
    title: 'Certifications',
    description: 'Préparez vos certifications professionnelles : Apple, Jamf 100/170/200, Microsoft MD-102 et MS-102.',
    icon: '🏆',
    color: 'yellow',
    order: 9,
    courses: module9Courses,
  },
];

// ─── HELPERS ───────────────────────────────────────────────────────────────

export function getAllCourses(): Course[] {
  return MODULES.flatMap((m) => m.courses);
}

export function getCourseBySlug(slug: string): Course | undefined {
  return getAllCourses().find((c) => c.slug === slug);
}

export function getModuleBySlug(slug: string): Module | undefined {
  return MODULES.find((m) => m.slug === slug);
}

export function getAdjacentCourses(slug: string): { prev: Course | null; next: Course | null } {
  const all = getAllCourses();
  const idx = all.findIndex((c) => c.slug === slug);
  return {
    prev: idx > 0 ? all[idx - 1] : null,
    next: idx < all.length - 1 ? all[idx + 1] : null,
  };
}

export function getCoursesByModule(moduleId: string): Course[] {
  return getAllCourses().filter((c) => c.moduleId === moduleId);
}

export function getCoursesByLevel(level: Level): Course[] {
  return getAllCourses().filter((c) => c.level === level);
}

export function getCoursesByTool(tool: Tool): Course[] {
  return getAllCourses().filter((c) => c.tools.includes(tool));
}

export const STATS = {
  totalModules: MODULES.length,
  totalCourses: getAllCourses().length,
  totalDuration: '80+ heures',
  certifications: 7,
};

export function getModuleForCourse(course: Course): Module | undefined {
  return MODULES.find((m) => m.id === course.moduleId);
}

export function getFeaturedCourses(): Course[] {
  // First course of each of the first 3 modules
  return MODULES.slice(0, 3).map((m) => m.courses[0]).filter(Boolean);
}
